name: Check-commit-messages-in-push

on: [push]

jobs:
  Check-commit-messages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Check the commit messages
        uses: mristin/opinionated-commit-message@v2.3.1
        with:
          path-to-additional-verbs: additional-verbs-in-imperative-mood.txt

      - name: READ HERE ON FAILURE FOR MORE INSTRUCTIONS
        if: ${{ failure() }}
        run: |
          echo \
            "The one or more commit messages do not fit our style guide." \
            "Please inspect carefully the error messages above and edit the commit messages." \
            "See the contributing guidelines at: " \
            "https://github.com/pschanely/CrossHair/blob/master/doc/contributing.md#write-commit-message"